package ma.chinespirit.parlance

import java.sql.PreparedStatement
import javax.sql.DataSource
import scala.util.Using

/** A read & write data repository
  *
  * @tparam EC
  *   'Entity Creator', which should have all fields of E minus those auto-generated by the database. Can be the same type as E.
  * @tparam E
  *   database entity class
  * @tparam ID
  *   id type of E
  */
open class Repo[EC, E, ID](
    injectedScopes: Vector[Scope[E]] = Vector.empty[Scope[E]],
    val observers: Vector[RepoObserver[EC, E]] = Vector.empty[RepoObserver[EC, E]]
)(using
    meta: EntityMeta[E],
    ib: InsertBuilder[EC, E]
) extends ImmutableRepo[E, ID](injectedScopes):

  // --- hook collection helpers ---

  private lazy val _collectOnUpdate: Vector[SetClause] =
    finalScopes.flatMap(_.onUpdate(meta))

  private lazy val _collectRewriteDelete: Vector[SetClause] =
    finalScopes.flatMap(_.rewriteDelete(meta))

  private lazy val _collectConditions: Vector[WhereFrag] =
    finalScopes.flatMap(_.conditions(meta))

  private lazy val _hasMutationHooks: Boolean =
    _collectOnUpdate.nonEmpty || _collectRewriteDelete.nonEmpty

  /** SQL column names that mutation hooks will set — structured access, no string parsing. */
  private lazy val _hookColumnNames: Set[String] =
    (_collectOnUpdate ++ _collectRewriteDelete).map(_.col.sqlName.toLowerCase).toSet

  // --- observer dispatch ---

  protected def fireDeleting(entity: E)(using DbCon[?]): Unit =
    if observers.nonEmpty then observers.foreach(_.deleting(entity))

  protected def fireDeleted(entity: E)(using DbCon[?]): Unit =
    if observers.nonEmpty then observers.foreach(_.deleted(entity))

  /** Build WHERE sql + params + writer from pk id and scope conditions */
  private def buildMutationWhere(id: ID): (String, Seq[Any], FragWriter) =
    val conditions = _collectConditions
    val pkSql = s"${meta.primaryKey.sqlName} = ?"
    if conditions.isEmpty then (s" WHERE $pkSql", Seq(id), FragWriter.fromKeys(Vector(id.asInstanceOf[Any])))
    else
      val condSql = conditions.map(_.sqlString).mkString(" AND ", " AND ", "")
      val allParams = Seq(id) ++ conditions.flatMap(_.params)
      val writer: FragWriter = (ps, pos) =>
        ps.setObject(pos, id)
        var p = pos + 1
        for c <- conditions do p = c.writer.write(ps, p)
        p
      (s" WHERE $pkSql$condSql", allParams, writer)

  // --- DELETE methods ---

  /** Deletes an entity using its id */
  def delete(entity: E)(using DbCon[? <: SupportsMutations]): Unit =
    fireDeleting(entity)
    deleteByIdCount(extractPk(entity).asInstanceOf[ID])
    fireDeleted(entity)

  /** Deletes an entity using its id */
  def deleteById(id: ID)(using con: DbCon[? <: SupportsMutations]): Unit =
    if observers.nonEmpty then
      findById(id).foreach: entity =>
        fireDeleting(entity)
        deleteByIdCount(id)
        fireDeleted(entity)
    else
      deleteByIdCount(id)

  private def deleteByIdCount(id: ID)(using con: DbCon[? <: SupportsMutations]): Int =
    if _collectRewriteDelete.nonEmpty then
      // Rewrite DELETE as UPDATE SET <rewriteDelete clauses>, <onUpdate clauses>
      val allSetClauses = _collectRewriteDelete ++ _collectOnUpdate
      val setSql = allSetClauses.map(_.sqlString).mkString(", ")
      val (whereSql, whereParams, whereWriter) = buildMutationWhere(id)
      val sql = s"UPDATE ${meta.tableName} SET $setSql$whereSql"
      val allParams = allSetClauses.flatMap(_.params) ++ whereParams
      val writer: FragWriter = (ps, pos) =>
        var p = pos
        for c <- allSetClauses do p = c.writer.write(ps, p)
        whereWriter.write(ps, p)
      Frag(sql, allParams, writer).update.run()
    else
      // No rewrite, but scope conditions apply to DELETE
      val (whereSql, whereParams, whereWriter) = buildMutationWhere(id)
      val sql = s"DELETE FROM ${meta.tableName}$whereSql"
      Frag(sql, whereParams, whereWriter).update.run()

  /** Deletes ALL entities */
  def truncate()(using con: DbCon[? <: SupportsMutations]): Unit =
    val sql = con.databaseType.renderTruncate(meta.tableName)
    Frag(sql, Vector.empty, FragWriter.empty).update.run()

  /** Delete all provided entities */
  def deleteAll(entities: Iterable[E])(using DbCon[? <: SupportsMutations]): BatchUpdateResult =
    var count = 0L
    entities.foreach { e =>
      count += deleteByIdCount(extractPk(e).asInstanceOf[ID])
    }
    BatchUpdateResult.Success(count)

  /** Deletes all entities with an Iterable of ids */
  def deleteAllById(ids: Iterable[ID])(using DbCon[? <: SupportsMutations]): BatchUpdateResult =
    var count = 0L
    ids.foreach { id =>
      count += deleteByIdCount(id)
    }
    BatchUpdateResult.Success(count)

  // --- INSERT methods ---

  /** Insert entity without returning or firing observer events. */
  def rawInsert(entityCreator: EC)(using DbCon[?]): Unit =
    ib.insert(entityCreator)

  /** Insert all entities without returning or firing observer events. */
  def rawInsertAll(entityCreators: Iterable[EC])(using DbCon[?]): Unit =
    ib.insertAll(entityCreators)

  /** Insert and return entity, firing creating/created observer events. */
  def create[D <: DatabaseType](entityCreator: EC)(using con: DbCon[D], cr: CanReturn[EC, E, D]): E =
    if observers.nonEmpty then
      observers.foreach(_.creating(entityCreator))
    val result = ib.insertReturning(entityCreator)
    con.trackLoaded(meta.tableName, extractPk(result), result)
    if observers.nonEmpty then
      observers.foreach(_.created(result))
    result

  /** Insert all and return entities without firing observer events. */
  def rawInsertAllReturning[D <: DatabaseType](
      entityCreators: Iterable[EC]
  )(using con: DbCon[D], cr: CanReturn[EC, E, D]): Vector[E] =
    val results = ib.insertAllReturning(entityCreators)
    results.foreach(e => con.trackLoaded(meta.tableName, extractPk(e), e))
    results

  // --- UPDATE methods ---

  /** Update the entity */
  def update(entity: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    if observers.nonEmpty then
      observers.foreach(_.updating(entity))
    updateInternal(entity)
    if observers.nonEmpty then
      observers.foreach(_.updated(entity))
  end update

  private def updateInternal(entity: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    val entityProduct = entity.asInstanceOf[Product]
    val columns = meta.columns
    val codecs = meta.elementCodecs

    // Build SET clauses for entity fields (excluding PK and columns covered by hooks)
    val hookCols = _hookColumnNames
    val entitySetParts = Vector.newBuilder[String]
    val entitySetIndices = Vector.newBuilder[Int]
    var i = 0
    while i < columns.length do
      if i != pkIndex && !hookCols.contains(columns(i).sqlName.toLowerCase) then
        entitySetParts += s"${columns(i).sqlName} = ${codecs(i).queryRepr}"
        entitySetIndices += i
      i += 1
    val setParts = entitySetParts.result()
    val setIndices = entitySetIndices.result()

    // Append onUpdate hook clauses
    val hookClauses = _collectOnUpdate
    val hookSetSql = hookClauses.map(_.sqlString)
    val allSetSql = (setParts ++ hookSetSql).mkString(", ")

    val (whereSql, whereParams, whereWriter) = buildMutationWhere(
      entityProduct.productElement(pkIndex).asInstanceOf[ID]
    )
    val sql = s"UPDATE ${meta.tableName} SET $allSetSql$whereSql"

    val allParams =
      setIndices.map(idx => entityProduct.productElement(idx)) ++
        hookClauses.flatMap(_.params) ++
        whereParams

    Frag(
      sql,
      allParams,
      (ps, pos) =>
        var p = pos
        // Write entity fields
        for idx <- setIndices do
          val codec = codecs(idx).asInstanceOf[DbCodec[Any]]
          codec.writeSingle(entityProduct.productElement(idx), ps, p)
          p += codec.cols.length
        // Write hook params
        for c <- hookClauses do p = c.writer.write(ps, p)
        // Write WHERE params
        whereWriter.write(ps, p)
    ).update.run()
  end updateInternal

  /** Update all entities */
  def updateAll(entities: Iterable[E])(using DbCon[? <: SupportsMutations]): BatchUpdateResult =
    var count = 0L
    entities.foreach { e =>
      updateInternal(e); count += 1
    }
    BatchUpdateResult.Success(count)

  /** Update only the changed fields between original and current entity */
  def updatePartial(original: E, current: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    if observers.nonEmpty then
      observers.foreach(_.updating(current))
    updatePartialInternal(original, current)
    if observers.nonEmpty then
      observers.foreach(_.updated(current))
  end updatePartial

  private def updatePartialInternal(original: E, current: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    val origProduct = original.asInstanceOf[Product]
    val currProduct = current.asInstanceOf[Product]
    val origId = origProduct.productElement(pkIndex)
    val currId = currProduct.productElement(pkIndex)
    require(origId == currId, s"updatePartial requires same id, got $origId != $currId")

    val arity = origProduct.productArity
    val changed = Vector.newBuilder[Int]
    var i = 0
    while i < arity do
      if i != pkIndex && origProduct.productElement(i) != currProduct.productElement(i)
      then changed += i
      i += 1
    val changedIndices = changed.result()

    val hookClauses = _collectOnUpdate
    if changedIndices.isEmpty && hookClauses.isEmpty then return

    val columns = meta.columns
    val codecs = meta.elementCodecs
    val hookCols = _hookColumnNames

    // Filter out changed fields that are covered by hooks
    val filteredIndices = changedIndices.filterNot(idx => hookCols.contains(columns(idx).sqlName.toLowerCase))

    val entitySetClauses = filteredIndices.map(idx => s"${columns(idx).sqlName} = ${codecs(idx).queryRepr}")
    val hookSetClauses = hookClauses.map(_.sqlString)
    val allSetSql = (entitySetClauses ++ hookSetClauses).mkString(", ")

    // If nothing to set (no changes, no hooks), skip
    if allSetSql.isEmpty then return

    val (whereSql, whereParams, whereWriter) = buildMutationWhere(currId.asInstanceOf[ID])
    val sql = s"UPDATE ${meta.tableName} SET $allSetSql$whereSql"

    val allParams =
      filteredIndices.map(idx => currProduct.productElement(idx)) ++
        hookClauses.flatMap(_.params) ++
        whereParams

    Frag(
      sql,
      allParams,
      (ps, pos) =>
        var p = pos
        for idx <- filteredIndices do
          val codec = codecs(idx).asInstanceOf[DbCodec[Any]]
          codec.writeSingle(currProduct.productElement(idx), ps, p)
          p += codec.cols.length
        for c <- hookClauses do p = c.writer.write(ps, p)
        whereWriter.write(ps, p)
    ).update.run()
  end updatePartialInternal

  /** Save entity: partial update if tracked, check DB if untracked, insert if not found. */
  def save(entity: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    val pkValue = extractPk(entity)
    con.getOriginal(meta.tableName, pkValue) match
      case Some(original) =>
        // Tracked — surgical update
        if observers.nonEmpty then observers.foreach(_.updating(entity))
        updatePartialInternal(original.asInstanceOf[E], entity)
        if observers.nonEmpty then observers.foreach(_.updated(entity))
      case None =>
        // Untracked — check DB
        findById(pkValue.asInstanceOf[ID]) match
          case Some(existing) =>
            // Found in DB — update
            if observers.nonEmpty then observers.foreach(_.updating(entity))
            updatePartialInternal(existing, entity)
            if observers.nonEmpty then observers.foreach(_.updated(entity))
          case None =>
            // Not in DB — insert
            if observers.nonEmpty then observers.foreach(_.creating(entity))
            insertByEntity(entity)
            con.trackLoaded(meta.tableName, pkValue, entity)
            if observers.nonEmpty then observers.foreach(_.created(entity))

  /** Insert a full entity (including PK) without conflict handling. */
  private def insertByEntity(entity: E)(using con: DbCon[? <: SupportsMutations]): Unit =
    val columns = meta.columns
    val codecs = meta.elementCodecs
    val colNames = columns.map(_.sqlName).mkString(", ")
    val placeholders = codecs.map(_.queryRepr).mkString(", ")
    val sql = s"INSERT INTO ${meta.tableName} ($colNames) VALUES ($placeholders)"
    val entityProduct = entity.asInstanceOf[Product]
    Frag(
      sql,
      Seq.empty,
      (ps, pos) =>
        var p = pos
        var i = 0
        while i < columns.length do
          val codec = codecs(i).asInstanceOf[DbCodec[Any]]
          codec.writeSingle(entityProduct.productElement(i), ps, p)
          p += codec.cols.length
          i += 1
        p
    ).update.run()

  /** Insert with conflict handling. */
  def insertOnConflict(entityCreator: EC, target: ConflictTarget, action: ConflictAction)(using DbCon[? <: SupportsMutations]): Unit =
    ib.insertOnConflict(entityCreator, target, action)

  /** Insert with conflict handling, updating all EC columns on conflict. */
  def insertOnConflictUpdateAll(entityCreator: EC, target: ConflictTarget)(using DbCon[? <: SupportsMutations]): Unit =
    ib.insertOnConflictUpdateAll(entityCreator, target)

  /** Bulk insert, skipping rows that conflict. Returns the number of rows actually inserted. */
  def insertAllIgnoring(entityCreators: Iterable[EC])(using DbCon[? <: SupportsMutations]): Int =
    ib.insertAllIgnoring(entityCreators)

  /** Find an existing entity matching the predicate, or insert a new one. */
  def firstOrCreate[D <: DatabaseType](predicate: WhereFrag, creator: => EC)(using con: DbTx[D], cr: CanReturn[EC, E, D]): E =
    val found = applyScopes(
      QueryBuilder.build0[E, Columns[E]](meta, meta, new Columns[E](meta.columns))
    ).where(predicate).first()
    found match
      case Some(entity) =>
        entity
      case None =>
        val ec = creator
        if observers.nonEmpty then
          observers.foreach(_.creating(ec))
        val result = ib.insertReturning(ec)
        con.trackLoaded(meta.tableName, extractPk(result), result)
        if observers.nonEmpty then
          observers.foreach(_.created(result))
        result

  /** Find and update an existing entity, or insert a new one. */
  def updateOrCreate[D <: SupportsMutations](predicate: WhereFrag, creator: => EC, updater: E => E)(using
      con: DbTx[D],
      cr: CanReturn[EC, E, D]
  ): E =
    val found = applyScopes(
      QueryBuilder.build0[E, Columns[E]](meta, meta, new Columns[E](meta.columns))
    ).where(predicate).first()
    found match
      case Some(existing) =>
        val updated = updater(existing)
        update(updated)
        updated
      case None =>
        val ec = creator
        if observers.nonEmpty then
          observers.foreach(_.creating(ec))
        val result = ib.insertReturning(ec)
        con.trackLoaded(meta.tableName, extractPk(result), result)
        if observers.nonEmpty then
          observers.foreach(_.created(result))
        result

  /** Touch an entity, setting its @updatedAt column to CURRENT_TIMESTAMP. */
  def touch(entity: E)(using hasUpdatedAt: HasUpdatedAt[E], con: DbCon[? <: SupportsMutations]): Unit =
    val id = extractPk(entity)
    val conditions = _collectConditions
    val pkSql = s"${entityMeta.primaryKey.sqlName} = ?"
    if conditions.isEmpty then
      Frag(
        s"UPDATE ${entityMeta.tableName} SET ${hasUpdatedAt.column.sqlName} = CURRENT_TIMESTAMP WHERE $pkSql",
        Seq(id),
        FragWriter.fromKeys(Vector(id))
      ).update.run()
    else
      val condSql = conditions.map(_.sqlString).mkString(" AND ", " AND ", "")
      val allParams = Seq(id) ++ conditions.flatMap(_.params)
      val writer: FragWriter = (ps, pos) =>
        ps.setObject(pos, id)
        var p = pos + 1
        for c <- conditions do p = c.writer.write(ps, p)
        p
      Frag(
        s"UPDATE ${entityMeta.tableName} SET ${hasUpdatedAt.column.sqlName} = CURRENT_TIMESTAMP WHERE $pkSql$condSql",
        allParams,
        writer
      ).update.run()
  end touch

  /** Re-fetch the entity from the database using its primary key. */
  def refresh(entity: E)(using DbCon[?]): E =
    val id = extractPk(entity).asInstanceOf[ID]
    findById(id).getOrElse(
      throw QueryBuilderException(s"Entity not found for refresh")
    )

end Repo
