drop table if exists qb_mut_item;
create table qb_mut_item (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    amount int not null default 0
);
insert into qb_mut_item values (1, 'Alpha', 10);
insert into qb_mut_item values (2, 'Beta', 20);
insert into qb_mut_item values (3, 'Gamma', 30);
alter sequence qb_mut_item_id_seq restart with 4;
