DROP TABLE IF EXISTS sd_user CASCADE;
CREATE TABLE sd_user (
  id BIGINT PRIMARY KEY,
  name VARCHAR NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE
);
INSERT INTO sd_user VALUES (1, 'Alice', NULL);
INSERT INTO sd_user VALUES (2, 'Bob', NULL);
INSERT INTO sd_user VALUES (3, 'Carol', TIMESTAMP WITH TIME ZONE '2025-01-01T00:00:00Z');
INSERT INTO sd_user VALUES (4, 'Dave', TIMESTAMP WITH TIME ZONE '2025-06-15T12:00:00Z');
