DROP TABLE IF EXISTS ts_item CASCADE;
CREATE TABLE ts_item (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE '2000-01-01T00:00:00Z',
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE '2000-01-01T00:00:00Z',
  deleted_at TIMESTAMP WITH TIME ZONE
);
